language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
jobs:
  include:
    - stage: test
      script: "yarn test"
    - stage: deploy
      before_install: "openssl aes-256-cbc -K $encrypted_32b6c04b6d48_key -iv $encrypted_32b6c04b6d48_iv -in deploy-key.enc -out ~/.ssh/deploy-key -d"
      script: "scripts/deploy.sh"
stages:
  - test
  - name: deploy
    if: type != pull_request