language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn test --runInBand --forceExit
notifications:
  email:
    on_success: never
    on_failure: always
